### ISSUE TITLE
[Feature Request] Tabletop Simulator Implementation

### ISSUE THREAD

**Issue by Ucda1212** [TootiFruti/FOSS-CCS#1]
Could you add the cards to TTS?

**Comment by TootiFruti** [comment]
can you elaborate what TTS is? It's my first time hearing about it.

**Comment by Oakchris1955** [comment]
A game on Steam where one can create their own board/card games. Unfortunately, it costs 20 bucks

**Comment by TootiFruti** [comment]
oh, then it wont be "Free" (the first F from FOSS-CCS) 
:(
