### ISSUE TITLE
Card Proposal: nmcil

### ISSUE THREAD

**Issue by Deepthought73** [TootiFruti/FOSS-CCS#2]
Hi, 

I had an idea for a new card: nmcli. I didn't open a pull request, since you probably want to reformat the card a little in order to keep a nice consistent layout.

![my_card](https://github.com/TootiFruti/FOSS-CCS/assets/94146136/90cfb672-1485-4ddf-9419-f89adc152ff3)

Nmcli
CLI Util
HP - 71280
NTDP - 0
Card type - silver
Popularity - A
User friendliness - 60%
Special attack - You delete all configured network connections of your opponent who forgot all passwords. Your opponent has to give away all cards requiring network connection.

I'm not sure whether I understood NTDP.

Nice work!

**Comment by TootiFruti** [comment]
This is Great. Your contribution is highly appreciated. 
OhYou should open a PR, just paste all the project files in the project file directory and you are all good. 
Basically NTDP is the dependencies.

**Comment by Deepthought73** [comment]
The problem with the messed up text holds for all cards. I guess, that the browser has issues displaying the fonts. When you open the svg with inkscape, the issue should be fixed.

**Comment by TootiFruti** [comment]
so can you upload the svg file

**Comment by TootiFruti** [comment]
now i see, yeah the svg file is all messed up but the png file is good.
so now just put the nmcli.png in the root directory too with name being "FOSS-CCS - NMCLI.png" and i'll merge the pr. 
and any socials that you want me to put for the "CONTRIBUTORS.md" file ;D

**Comment by Deepthought73** [comment]
My Github account is just fine. Thanks :)
